SP-317 - Replace Timestamp with Counter
mx51/spi-client-java pull request #38
Opened 2021-06-21 11:04 UTC by AliAkiltayev

Replaced timestamp with counter in according with JS library

2021-06-28 03:29 UTC, mattgresham approved these changes
Looks good to me.

Just remember that to test this with the VAA, the protocol needs to be bumped like in this ticket - https://mx51.atlassian.net/browse/SP-712

2021-06-29 06:45 UTC, mattgresham commented on client/src/main/java/io/mx51/spi/model/Message.java
> +        System.out.println(dateTimeStamp);
A small thing, could you remove this output please

2021-06-29 21:52 UTC, RaymondK-mx51 requested changes

2021-06-30 06:05 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/MessageStamp.java
> +    private Integer posCounter;
should this be `int`?

2021-06-30 06:05 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/Message.java
> +    private Integer posCounter;
should this be `int`

2021-06-30 06:06 UTC, RaymondK-mx51 reviewed
Should all occurences of `Integer` be changed to `int`?

2021-06-30 06:09 UTC, AliAkiltayev commented
> Should all occurrences of `Integer` be changed to `int`?

Ok, got it

2021-06-30 06:12 UTC, AliAkiltayev commented
> Should all occurrences of `Integer` be changed to `int`?

How about responseCode in DeviceAddressStatus class? Should I also change it?

2021-06-30 06:45 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/Message.java
> +    private Integer posCounter;
> > Should all occurrences of `Integer` be changed to `int`?
> 
> How about responseCode in DeviceAddressStatus class? Should I also change it?

Yes Please

2021-07-01 06:04 UTC, RaymondK-mx51 approved these changes

2021-07-01 06:05 UTC, merged