Feature/SP-314: Added get transaction feature
mx51/spi-client-java pull request #48
Opened 2021-07-20 11:39 UTC by AliAkiltayev

2021-07-21 05:58 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionRequest.java
> +        Map<String, Object> data = new HashMap<>();
can you please add the final word:

`final Map<String, Object> data = new HashMap<String, Object>();`

2021-07-21 06:02 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +            Map<String, Object> message = _m.getDataMapValue("tx");
same here please, `final`

2021-07-21 06:04 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/Message.java
> +    public Map<String, Object> data;
any reason this has been made public?

2021-07-21 06:18 UTC, AliAkiltayev commented on client/src/main/java/io/mx51/spi/model/Message.java
> +    public Map<String, Object> data;
No, it was set public by mistake

2021-07-21 06:34 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/Spi.java
>                      // Let's get the last transaction to check what we might have missed out on.
can you please remove the word `last` thanks

2021-07-21 06:54 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +            String cr = _m.getDataStringValue("customer_receipt");
`final` keyword

2021-07-21 06:54 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +            String mr = _m.getDataStringValue("merchant_receipt");
`final` keyword

2021-07-21 06:54 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
`final` keyword

2021-07-21 08:33 UTC, RaymondK-mx51 requested changes
@AliAkiltayev see the comments, thanks

2021-07-21 09:44 UTC, AliAkiltayev commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
I've removed empty GetTransactionResponse constructor, since setting _m as final without initial value does not allow empty constructor in the class.

2021-07-26 03:38 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
the final keyword is still missing or am I not understanding something?

2021-07-26 04:22 UTC, AliAkiltayev commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
You mean on Message right?

2021-07-26 04:25 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
that's correct

2021-07-26 04:48 UTC, AliAkiltayev commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
So now you see Message as final?

2021-07-26 05:19 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
![image](https://user-images.githubusercontent.com/16125144/126936864-8c90eff3-e8ad-4340-9f32-4c1e3d63ca19.png)

This is what I see in github.com

2021-07-26 05:43 UTC, AliAkiltayev commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
Could be GitHub issue. Please, check this link
https://github.com/mx51/spi-client-java/blob/feature/SP-314/client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java

2021-07-27 06:11 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/model/GetTransactionResponse.java
> +        private Message _m;
thanks

2021-07-27 06:12 UTC, RaymondK-mx51 approved these changes

2021-07-27 06:16 UTC, merged