feature/SP-167: Fixed tests and services
mx51/spi-client-java pull request #50
Opened 2021-07-26 12:59 UTC by AliAkiltayev

Previous SP-167 branch was not working properly, made these fixes for proper connection and auto resolution

2021-07-27 05:52 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/Spi.java
>              LOG.warn("Trying to auto resolve address, but device address has not changed.");
Can you change the log message to `"Could not communicate with device address service."`

2021-07-27 05:54 UTC, AliAkiltayev commented on client/src/main/java/io/mx51/spi/Spi.java
>              LOG.warn("Trying to auto resolve address, but device address has not changed.");
Changed

2021-07-27 05:54 UTC, RaymondK-mx51 commented on client/src/main/java/io/mx51/spi/Spi.java
> +        LOG.info("Address status#### " + deviceAddressStatus.getDeviceAddressResponseCode());
can you please remove this line? thanks

2021-07-27 05:57 UTC, RaymondK-mx51 requested changes
see comments

2021-07-27 06:01 UTC, AliAkiltayev commented on client/src/main/java/io/mx51/spi/Spi.java
> +        LOG.info("Address status#### " + deviceAddressStatus.getDeviceAddressResponseCode());
Removed

2021-08-01 23:04 UTC, RaymondK-mx51 commented
@DixusSlim can you please review this PR. Thanks

2021-08-11 04:46 UTC, closed without merging